// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_c3_sunday/test/features/home/api/datasources_impl/home_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:elevate_c3_sunday/config/api_result/api_result.dart' as _i9;
import 'package:elevate_c3_sunday/features/home/api/client/home_api_client.dart'
    as _i6;
import 'package:elevate_c3_sunday/features/home/api/models/response/categories_response.dart'
    as _i3;
import 'package:elevate_c3_sunday/features/home/api/models/response/products_response.dart'
    as _i2;
import 'package:elevate_c3_sunday/features/home/data/datasources/home_local_datasource.dart'
    as _i4;
import 'package:elevate_c3_sunday/features/home/data/datasources/home_remote_datasource.dart'
    as _i5;
import 'package:elevate_c3_sunday/features/home/data/repos_impl/home_repo_impl.dart'
    as _i8;
import 'package:elevate_c3_sunday/features/home/domain/models/category_model.dart'
    as _i10;
import 'package:elevate_c3_sunday/features/home/domain/models/product_model.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductsResponse_0 extends _i1.SmartFake
    implements _i2.ProductsResponse {
  _FakeProductsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesResponse_1 extends _i1.SmartFake
    implements _i3.CategoriesResponse {
  _FakeCategoriesResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeLocalDataSource_2 extends _i1.SmartFake
    implements _i4.HomeLocalDataSource {
  _FakeHomeLocalDataSource_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeRemoteDataSource_3 extends _i1.SmartFake
    implements _i5.HomeRemoteDataSource {
  _FakeHomeRemoteDataSource_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeApiClient extends _i1.Mock implements _i6.HomeApiClient {
  MockHomeApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.ProductsResponse> getProducts({
    int? productPerPage = 10,
    int? pageNumber = 1,
    String? categoryId = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #productPerPage: productPerPage,
              #pageNumber: pageNumber,
              #categoryId: categoryId,
            }),
            returnValue: _i7.Future<_i2.ProductsResponse>.value(
              _FakeProductsResponse_0(
                this,
                Invocation.method(#getProducts, [], {
                  #productPerPage: productPerPage,
                  #pageNumber: pageNumber,
                  #categoryId: categoryId,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.ProductsResponse>);

  @override
  _i7.Future<_i3.CategoriesResponse> getCategories({
    int? categoryPerPage = 10,
    int? pageNumber = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [], {
              #categoryPerPage: categoryPerPage,
              #pageNumber: pageNumber,
            }),
            returnValue: _i7.Future<_i3.CategoriesResponse>.value(
              _FakeCategoriesResponse_1(
                this,
                Invocation.method(#getCategories, [], {
                  #categoryPerPage: categoryPerPage,
                  #pageNumber: pageNumber,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.CategoriesResponse>);
}

/// A class which mocks [HomeRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepoImpl extends _i1.Mock implements _i8.HomeRepoImpl {
  MockHomeRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.HomeLocalDataSource get homeLocalDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#homeLocalDataSource),
            returnValue: _FakeHomeLocalDataSource_2(
              this,
              Invocation.getter(#homeLocalDataSource),
            ),
          )
          as _i4.HomeLocalDataSource);

  @override
  _i5.HomeRemoteDataSource get homeRemoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#homeRemoteDataSource),
            returnValue: _FakeHomeRemoteDataSource_3(
              this,
              Invocation.getter(#homeRemoteDataSource),
            ),
          )
          as _i5.HomeRemoteDataSource);

  @override
  set homeLocalDataSource(_i4.HomeLocalDataSource? _homeLocalDataSource) =>
      super.noSuchMethod(
        Invocation.setter(#homeLocalDataSource, _homeLocalDataSource),
        returnValueForMissingStub: null,
      );

  @override
  set homeRemoteDataSource(_i5.HomeRemoteDataSource? _homeRemoteDataSource) =>
      super.noSuchMethod(
        Invocation.setter(#homeRemoteDataSource, _homeRemoteDataSource),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i9.ApiResult<List<_i10.CategoryModel>>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i7.Future<_i9.ApiResult<List<_i10.CategoryModel>>>.value(
                  _i11.dummyValue<_i9.ApiResult<List<_i10.CategoryModel>>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i7.Future<_i9.ApiResult<List<_i10.CategoryModel>>>);

  @override
  _i7.Future<List<_i12.ProductModel>> getProducts({
    String? categoryId,
    int? productPerPage,
    int? pageNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #categoryId: categoryId,
              #productPerPage: productPerPage,
              #pageNumber: pageNumber,
            }),
            returnValue: _i7.Future<List<_i12.ProductModel>>.value(
              <_i12.ProductModel>[],
            ),
          )
          as _i7.Future<List<_i12.ProductModel>>);
}
